services:
  db:
    build: ./db

    container_name: postgres18

    restart: always

    shm_size: 128mb

    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru_RU.UTF-8"

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      # Скрипты из ./sql выполняются автоматически при ПЕРВОМ запуске (пока БД пустая)
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    image: rzps-app:1.0
    depends_on:
      - db
    env_file:
      - ./app/.env
    # Интерактивный режим: чтобы можно было вводить данные с клавиатуры
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
